### ISSUE TITLE
Add auto backport functionality to backport PRs for releases

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/logstash-output-opensearch#115]
meta issue https://github.com/opensearch-project/opensearch-plugins/issues/108

- [x] Add auto-backport PR creation Github action to make sure all the PRs are backported for a particular release. 
Related documentation: https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md

- [x] Add documentation for the same.

**Comment by VachaShah** [comment]
Hi @naveentatikonda thank you adding this! Can you also update this workflow and add an auto delete workflow as mentioned in https://github.com/opensearch-project/opensearch-plugins/blob/main/BACKPORT.md?

**Comment by naveentatikonda** [comment]
> Hi @naveentatikonda thank you adding this! Can you also update this workflow and add an auto delete workflow as mentioned in https://github.com/opensearch-project/opensearch-plugins/blob/main/BACKPORT.md?

Sure, will add it.
