### ISSUE TITLE
Requesting 'logstash-input-opensearch' plugin

### ISSUE THREAD

**Issue by camAtGitHub** [opensearch-project/logstash-output-opensearch#120]
Sorry I realise this isn't exactly what this repo is about, but I figure it's the closet there is...

**Is your feature request related to a problem? Please describe.**
Please create a `logstash-input-opensearch` plugin

**Describe the solution you'd like**
If for any reason, I'd need to export / re-process / reindex large amounts of logs data I no longer can.   
Running Logstash version `7.16.2` against OpenSearch `1.2.3` with compatibility turned off you get the error message: `Could not connect to a compatible version of Elasticsearch`

The solution I'd like is a logstash-input-plugin that worked against opensearch.

**Additional context**
While I realise its not this repo's responsibility, perhaps you can notify the right persons to request it?  Other perhaps point me in the right direction for who to ask?

Many Thanks

**Comment by VijayanB** [comment]
HI @camAtGitHub Thanks for raising issue. We are working on adding new plugin . You can track this request [here](https://github.com/opensearch-project/opensearch-plugins/issues/121)

**Comment by VijayanB** [comment]
I am closing this ticket since it is tracked in other place. Please comment in other ticket for any additional questions. Thanks.
