### ISSUE TITLE
[BUG] Cannot install template for OpenSearch 2.x

### ISSUE THREAD

**Issue by shdubsh** [opensearch-project/logstash-output-opensearch#145]
**Describe the bug**
Logstash is unable to install a template against OpenSearch 2.0.0 due to a missing template file.

**To Reproduce**
1. Install opensearch 2.0.0 and logstash-oss 7.16.3 and logstash-output-opensearch plugin 1.2.0
2. Configure an input and a minimal opensearch output excluding template settings
3. Start OpenSearch then Logstash
4. Observe logstash logs:
```
[2022-06-02T21:49:18,561][ERROR][logstash.outputs.opensearch][main] Failed to install template {
  :message=>"Failed to load default template for OpenSearch v2 with ECS disabled; caused by: #<ArgumentError: Template file '/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/templates/ecs-disabled/2x.json' could not be found>", 
  :exception=>RuntimeError, 
  :backtrace=>[
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/template_manager.rb:33:in `load_default_template'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/template_manager.rb:21:in `install_template'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch.rb:412:in `install_template'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch.rb:247:in `finish_register'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch.rb:224:in `block in register'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/plugin_mixins/opensearch/common.rb:83:in `block in after_successful_connection'"
    ]
  }
```
**Expected behavior**
Logstash should install a template and start successfully

**Plugins**
logstash-output-opensearch

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - OS: Debian Buster

**Additional Context**
The user can configure the 1.x template (`template => "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/templates/ecs-disabled/1x.json"`) and Logstash will install it and start processing.

**Comment by nickytd** [comment]
Hi

Same observation. Please add the expected 2x.json template.
Thanks

**Comment by brijos** [comment]
The team released 2.0.1 on 6/16 which address some compatibility issues. After upgrading are you still running into the same issue?

**Comment by abbeNation** [comment]
Hello, 

Same observation. 
Used logstash 7.16.3 and tested with both opensearch 2.0.0 and 2.0.1, the problem persists unfortunately.
Doesn't logstash needs update to be shipped with a new 2x.json template file in order to fix this issue?

/Albin.

**Comment by datrh** [comment]
Any news about this?

**Comment by trunet** [comment]
Looks like this was fixed here https://github.com/opensearch-project/logstash-output-opensearch/pull/146 but there's no release with it.

**Comment by prudhvigodithi** [comment]
One more issue released to this topic
https://github.com/opensearch-project/opensearch-devops/issues/85
@bbarani @dk-do @dblock
