### ISSUE TITLE
logstash-oss-with-opensearch-output-plugin images support logstash8.x  and support output opensearch2.x

### ISSUE THREAD

**Issue by mazhiyuan-aiit** [opensearch-project/logstash-output-opensearch#161]
**Is your feature request related to a problem? Please describe.**
logstash-oss-with-opensearch-output-plugin images update with the latest LogStash and OpenSearch Images it would be fantastic

**Describe the solution you'd like**
I want the logstash-oss-with-opensearch-output-plugin images to be updated in a timely manner. I can use the new features.

**Describe alternatives you've considered**

**Additional context**
contact me at any time. thanks

**Comment by deepdatta** [comment]
https://hub.docker.com/r/opensearchproject/logstash-oss-with-opensearch-output-plugin/tags?page=1&ordering=last_updated&name=8.4.0 is now available
