### ISSUE TITLE
Update dependencies to be compatible with 8.4.0 logstash-oss default installation

### ISSUE THREAD

**Issue by ryn9** [opensearch-project/logstash-output-opensearch#167]
**Is your feature request related to a problem? Please describe.**
Yes. 
Installation of the 1.3.0 plugin fails against a default Logstash OSS 8.4.0 installation
```
$ logstash-plugin install --version 1.3.0 logstash-output-opensearch
Using bundled JDK: /usr/share/logstash/jdk
Validating logstash-output-opensearch-1.3.0
Resolving mixin dependencies
Updating mixin dependencies logstash-mixin-ecs_compatibility_support
Bundler attempted to update logstash-mixin-ecs_compatibility_support but its version stayed the same
Installing logstash-output-opensearch
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "aws-sdk-core":
  In snapshot (Gemfile.lock):
    aws-sdk-core (= 3.131.5)

  In Gemfile:
    logstash-output-opensearch (= 1.3.0) was resolved to 1.3.0, which depends on
      aws-sdk (>= 2.11.632, ~> 2) was resolved to 2.11.632, which depends on
        aws-sdk-resources (= 2.11.632) was resolved to 2.11.632, which depends on
          aws-sdk-core (= 2.11.632)

    logstash-integration-aws was resolved to 7.0.0, which depends on
      aws-sdk-core (~> 3)
```

**Describe the solution you'd like**
Please fix dependencies of the plugin to not conflict with needed dependencies of logstash-integration-aws, which is not bundled by default

**Describe alternatives you've considered**
Installed against Logstash OSS 8.3.3 installation, which does not bundle logstash-integration-aws by default

**Comment by ryn9** [comment]
Looks like work for this plugin using aws sdk 3 is already underway ...
https://github.com/opensearch-project/logstash-output-opensearch/pull/171

Please don't close this issue until we know newest plugin works with logstash-oss  8.4.0+

**Comment by ryn9** [comment]
initial testing with logstash OSS 8.4.1 docker image and logstash-output-opensearch 2.0.0 is looking good
target is AWS hosted OpenSearch version 1.3

testing with this simple Dockerfile

```
FROM docker.elastic.co/logstash/logstash-oss:8.4.1-amd64
RUN logstash-plugin install --version 2.0.0 logstash-output-opensearch
```

**Comment by anubisg1** [comment]
this works and has been fixed.  i'd close it
