### ISSUE TITLE
[BUG] Latest plugin version is not available as a docker container

### ISSUE THREAD

**Issue by trunet** [opensearch-project/logstash-output-opensearch#173]
With the release of 1.3.0, would be nice to have it available on https://hub.docker.com/r/opensearchproject/logstash-oss-with-opensearch-output-plugin image as well.

**Comment by trunet** [comment]
Probably this relates to https://github.com/opensearch-project/logstash-output-opensearch/issues/154

**Comment by anubisg1** [comment]
plugins are always a nightmore to track, it would be best to build a new container the with all the plugins you might need...
an example Dockerfile is the following

```
ARG logstash_version
FROM docker.elastic.co/logstash/logstash:${logstash_version}
RUN bin/logstash-plugin install logstash-filter-translate
RUN bin/logstash-plugin install logstash-input-snmp
RUN bin/logstash-plugin install --version 2.0.0 logstash-output-opensearch
```

and you can you this to build it

```
VERSION=8.4.3
REGISTRY=my-registry.com

docker build . --build-arg logstash_version=$VERSION -t $REGISTRY/logstash/logstash-plugin:$VERSION
docker push $REGISTRY/logstash/logstash-plugin:$VERSION
```

**Comment by dblock** [comment]
See https://github.com/opensearch-project/logstash-output-opensearch/issues/230.
