### ISSUE TITLE
[BUG] - logstash-output-opensearch complains for cluster UUID while connecting to Amazon OpenSearch Serverless

### ISSUE THREAD

**Issue by prashanttct07** [opensearch-project/logstash-output-opensearch#186]
**Describe the bug**
Running the plugin gives following error when connecting with Amazon OpenSearch Serverless. 
`[2023-01-11T17:39:47,431][ERROR][logstash.outputs.opensearch][main] Unable to retrieve OpenSearch cluster uuid {:message=>"undefined method `[]' for nil:NilClass", :exception=>NoMethodError,`

This is an error message which is thrown but ingestion is working fine and I am able to see the document is OpenSearch Serverless collections. 

**To Reproduce**
1. Setup and install logstash with logstash-output-opensearch plugin
2. Setup OpenSearch Serverless collections
3. Use below sample code to run the logstash, save file as logstash-example.conf
```
input {
   stdin { }
}
output {
  opensearch {
    ecs_compatibility => disabled
    index => "logstash-sample"
    hosts => "https://<add-your-collection-url>:443"
    auth_type => {
      type => 'aws_iam'
      aws_access_key_id => '<secret-key>'
      aws_secret_access_key => '<secret-access-key>'
      region => '<region>'
      service_name => 'aoss'
    }
    legacy_template => false
    default_server_major_version => 2
  }
}

```
4. Run the logstash as: 
`<path/to/your/logstash/dir>/bin/logstash -f logstash-example.conf`

5. See the error as mentioned above 

**Expected behavior**
There should not be any error and logstash should be able to index data to OpenSearch Serverless collections

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Version 12.6.2

**Comment by chadmyers** [comment]
The error seems to originate from `discover_cluster_uuid` which invokes `GET /` but gets an empty response. 
![image](https://github.com/opensearch-project/logstash-output-opensearch/assets/96477/caa0fc8c-3c99-4c3f-972a-32bd355d76b9)

I see that same thing on my OSS cluster: 
![image](https://github.com/opensearch-project/logstash-output-opensearch/assets/96477/70011a8d-0302-4dcb-99ec-3edb246948b3)

Is the cluster UUID needed? Perhaps we just do a nil check in `discover_cluster_uuid` and move on?

**Comment by chadmyers** [comment]
Can anyone confirm that they've got this plugin working with Opensearch Serverless?  What I'm trying to determine is if there's a bug in the plugin or if there's a problem with our configuration that's preventing the plugin from working.  Thanks!

**Comment by dblock** [comment]
@chadmyers want to help fix this one? I can help with code/review. Serverless doesn’t have the concept of a cluster - ideally we should be able to configure the plug-in enough that it doesn’t have to be polling the server at all, but something simpler could also be a solution

**Comment by dblock** [comment]
> logstash eventually stops because of it

While this is a problem, what led you to conclude that this happens because of this error?

**Comment by chadmyers** [comment]
> > logstash eventually stops because of it
> 
> While this is a problem, what led you to conclude that this happens because of this error?

I think this is a common Logstash problem - messages build up in the in-memory queue because it can't flush them to the output and then eventually logstash runs out of memory.  I think it's designed to do that. The basic problem is that the plugin can't hit OpenSearch Serverless. I'm still trying to figure out if it's an access policy setting on our end or a bug in the plugin or maybe both. 

I think we also have some Windows CP1252/ISO-8859-1 encoded messages coming in which may be tripping up the plugin so we're also looking at making sure everything coming into our logstash indexer box is utf-8 to eliminate that possible variable. It's something we've been meaning to do anyhow so this is as good a time as any to do it. Will report back if we find out more. Thank you for your notes.

**Comment by jomafe** [comment]
I'm facing this issue as well. This is a show stopper to consider AOSS as a sink for an existing Logstash environment. Is there any ETA for a solution?

**Comment by dblock** [comment]
@jomafe which is your actual issue? the error message in this one is innocuous - are you getting errors on messages with different encoding?

**Comment by chadmyers** [comment]
@dblock It's hard to tell if this error is unrelated/innocuous, or a symptom of a larger issue. At least in my experience, we could not get Logstash to successfully work with AOSS at all. It sounds like jomafe is having the same issue.

**Comment by dblock** [comment]
I can't confirm this, I was able to make it work with AOSS with this error in the logs. I basically followed the instructions in https://opensearch.org/docs/latest/tools/logstash/index/.

#### AWS Credentials and Endpoint

```
export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...
export AWS_SESSION_TOKEN=...
export ENDPOINT=https://.....us-west-2.aoss.amazonaws.com
export AWS_REGION=us-west-2
export SERVICE=es
```

### Latest Version of the Plugin

Built from source to make sure I have the latest.

```
cd ~/source/opensearch-project/logstash-output-opensearch/upstream-logstash-output-opensearch
./build.sh 
/Users/dblock/source/opensearch-project/logstash-output-opensearch/upstream-logstash-output-opensearch/builds/logstash-output-opensearch-2.0.2-arm64-darwin-21.gem
```

### Install LogStash

```
wget https://artifacts.elastic.co/downloads/logstash/logstash-8.12.1-darwin-x86_64.tar.gz
tar vfxz logstash-8.12.1-darwin-x86_64.tar.gz 
cd logstash-8.12.1
```

### Install Plugin

```
bin/logstash-plugin install /Users/dblock/source/opensearch-project/logstash-output-opensearch/upstream-logstash-output-opensearch/builds/logstash-output-opensearch-2.0.2-arm64-darwin-21.gem
```

```
Using bundled JDK: /Users/dblock/source/opensearch-project/logstash-issue-186/logstash-8.12.1/jdk.app/Contents/Home
warning: ignoring JAVA_TOOL_OPTIONS=-Dlog4j2.formatMsgNoLookups=true
Validating /Users/dblock/source/opensearch-project/logstash-output-opensearch/upstream-logstash-output-opensearch/builds/logstash-output-opensearch-2.0.2-arm64-darwin-21.gem
Installing logstash-output-opensearch
Installation successful
```

### Run Logstash

```
 bin/logstash -e "input { stdin { } } output {
   opensearch {
    ecs_compatibility => disabled
    index  => 'logstash-logs-%{+YYYY.MM.dd}'
    hosts => ['${ENDPOINT}:443']
    auth_type => {
      type => 'aws_iam'
      aws_access_key_id => '${AWS_ACCESS_KEY_ID}'
      aws_secret_access_key => '${AWS_SECRET_ACCESS_KEY}'
      session_token => '${AWS_SESSION_TOKEN}'
      region => '${AWS_REGION}'
      service_name => '${SERVICE}'
    }
    legacy_template => false
    default_server_major_version => 2
  }
 }"
```

Type a few "hello world" on the console

### Check Docs

```
$ awscurl --region=$AWS_REGION --service=$SERVICE $ENDPOINT/_cat/indices?v
health status index                                       uuid                 pri rep docs.count docs.deleted store.size pri.store.size
              logstash-logs-2024.02.13                    0Zf2oo0BiehDHTSpsLmp                  0            0         0b             0b
```

```
$ awscurl --region=$AWS_REGION --service=$SERVICE $ENDPOINT/logstash-logs-2024.02.13/_count  | jq ".count"
18
```

**Comment by dblock** [comment]
> @dblock at some point I realized the system still works after this error. Now I'm facing the "Encountered a retryable error (will retry with exponential backoff) {:code=>403, :url=>"https://myendpoint.eu-central-1.aoss.amazonaws.com:443/_bulk", :content_length=>1747}" even though the IAM user I'm using to connect is entitled to perform any action on any collection and index. Do I need to use a specific logstash version for this plugin to work properly?

For me this is always an auth problem. Let's do two things:

1. Check your version of logstash-output-opensearch, if needed make sure you're running 2.0.2 (https://rubygems.org/gems/logstash-output-opensearch).
2. Check that your credentials work against AOSS, e.g. `awscurl --region=$AWS_REGION --service=$SERVICE $ENDPOINT/_cat/indices?v`.
3. Check your plugin config for iam_auth
4. Check the IAM config under `auth_type`. See mine above that did work.

**Comment by jomafe** [comment]
I've added an IAM policy to the user allowing write actions for OpenSearch Serverless service and it started working. I don't see this specified anywhere in the service documentation. I thought the **Data access policies** from the OpenSearch Serverless service console were enough.

Anyway, thank you.

**Comment by dblock** [comment]
> I've added an IAM policy to the user allowing write actions for OpenSearch Serverless service and it started working. I thought the **Data access policies** from the OpenSearch Serverless service console were enough.

Glad it started working. Is there something we can add in this project to save time for the next person? Consider contributing to the READMEs?

**Comment by chadmyers** [comment]
Daniel and Jordi - I haven't had a chance to see if Logstash + AOSS is working for us yet but I wanted to thank you for your time in investigating this and I'm encouraged to see the progress you all have made.

**Comment by palashhedau** [comment]
Hi @jomafe, Yes, IAM permissions are required, along with a data access policy for accessing AOSS resources. IAM policies act as coarse-grained permissions, while data access policies act as fine-grained permissions for accessing resources. If a principal doesn't have IAM permissions, they will receive 403 errors when attempting to send requests to the AOSS collection.
