### ISSUE TITLE
List of Dependencies used

### ISSUE THREAD

**Issue by krishnapyde** [opensearch-project/logstash-output-opensearch#200]
**Describe the bug**
Hello Team, Need some urgent help 
We are looking to use this plugin in our project, and as part of this (as an org mandate) we need to declare all the dependencies of this plugin along with the license notice for each of the dependencies used.
We have earlier done the dependency extraction for Maven/Gradle-based projects. But this being a RUBY project and a plugin, we are not sure how to extract it.
We need help extracting all the dependencies of this project. Can you please help us with this? Or if there is a list already available, can you point us to it?

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dlvenable** [comment]
@krishnapyde ,

I'm not sure about a command-line tool to do this.

But, this data is available at rubygems.org.

For version 2.0.1 of this plugin:

https://rubygems.org/gems/logstash-output-opensearch/versions/2.0.1-java/dependencies

**Comment by wbeckler** [comment]
@krishnapyde did that answer your quesiton?
