### ISSUE TITLE
Backport encoding bug fix for AWS SigV4

### ISSUE THREAD

**Issue by dblock** [opensearch-project/logstash-output-opensearch#225]
**Is your feature request related to a problem? Please describe.**

Do we need to backport #217 to 1.3?

**Describe the solution you'd like**

AFAIK we don't because anyone can upgrade from logstash-output-opensearch 1.x to 2.x, but I could be wrong. Are there reasons why this upgrade is not possible?

**Comment by dlvenable** [comment]
The primary change in 2.0 was updating to the AWS SDK v3. The fix in #217 appears compatible with AWS SDK v2.

I think we want to see if anybody needs this. If so, this could be done. There is a [`1.3`](https://github.com/opensearch-project/logstash-output-opensearch/tree/1.3) branch available for backporting.

I think we'd also need to backport changes to support automated releasing (updated certificates, perhaps release-drafter.yml)/

**Comment by dblock** [comment]
Let's close this.
