### ISSUE TITLE
[BUG] Unexpected behaviour if remote Opensearch response is not "common" 

### ISSUE THREAD

**Issue by zhavir** [opensearch-project/logstash-output-opensearch#236]
**Describe the bug**
I'm trying to setup my pipeline with the Logstash and OpenSearch plugin. The connection seems working fine until the client tries to read the response received by the remote Opensearch instance. 

**To Reproduce**
Difficult to reproduce because it is a self-hosted Opensearch instance with a proxy API on top

**Expected behavior**
no expectation raised 

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
![image](https://github.com/opensearch-project/logstash-output-opensearch/assets/8330235/24b0dc13-993d-417d-a061-4b096dac708a)

**Additional context**

**Comment by dblock** [comment]
Looks like the plugin always expects JSON. That feels by design, doesn't it?

**Comment by zhavir** [comment]
there was a problem from my side, I was sure that I was trying to contact directly an OpenSearch instance. Instead, it was an Logstash. I've solved the issue by using the http plugin
