### ISSUE TITLE
Lower the number of required approvers for CRs to 1

### ISSUE THREAD

**Issue by dblock** [opensearch-project/logstash-output-opensearch#242]
**Is your feature request related to a problem? Please describe.**

Currently PRs require 2 PR to be merged. This is slowing us down with only 1-2 active maintainers.

**Describe the solution you'd like**

Lower the number of approvers to 1.

**Additional context**

PRs like #237 sitting out here for weeks.

**Comment by dblock** [comment]
@asifsmohammed @dlvenable @oeyh?

**Comment by dlvenable** [comment]
I agree with this.

**Comment by oeyh** [comment]
I agree.

**Comment by dblock** [comment]
Looks like the majority of maintainers agree, I lowered the number of approvers required to 1.
