### ISSUE TITLE
Update to latest logstash 8.14.1

### ISSUE THREAD

**Issue by kingnarmer** [opensearch-project/logstash-output-opensearch#254]
**Is your feature request related to a problem? Please describe.**
Please update logstash-output-opensearch  to work with latest losgtash 8.14.1

**Describe the solution you'd like**
Release new image for **logstash-oss-with-opensearch-output-plugin** with logstash-oss 8.14.1 support.

**Describe alternatives you've considered**
none

**Additional context**
Take advantage of recent performance improvement in latest logstash .

**Comment by dblock** [comment]
This is a dup of https://github.com/opensearch-project/logstash-output-opensearch/issues/243.
