### ISSUE TITLE
Correct copyright notices to reflect Copyright OpenSearch Contributors

### ISSUE THREAD

**Issue by dblock** [opensearch-project/logstash-output-opensearch#51]
Coming from https://github.com/opensearch-project/.github/issues/21.

The correct copyright for open-source projects in opensearch-project is "Copyright OpenSearch Contributors". Please correct any places that say otherwise, especially where it says copyright Amazon. Make sure NOTICE.txt and README match. See https://github.com/opensearch-project/.github/pull/24 for an example.

**Comment by dblock** [comment]
The NOTICE file contents don't match.

**Comment by AMoo-Miki** [comment]
The correct header for [this one](https://github.com/opensearch-project/logstash-output-opensearch/blob/main/release/docker/build-docker-multi-arch.sh) is:

```
/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
```

**Comment by VijayanB** [comment]
@naveentatikonda can you update this as well? Thanks.
