### ISSUE TITLE
[BUG] Elasticsearch output fail - Could not connect to a compatible version of Elasticsearch

### ISSUE THREAD

**Issue by itsul** [opensearch-project/logstash-output-opensearch#54]
We use OpenSearch v1.0.0 with the latest logstash oss version from opensearch itself (https://opensearch.org/docs/clients/logstash/index/) . Both is running via docker(-compose).

**To Reproduce**
1. Run OpenSearch Elastic + Kibana
2. Setup logstash-oss container and configure elasticsearch as an output
3. Start logstash container

**Expected behavior**
Logstash should insert the entries into elasticsearch.

**Plugins**
Default installation, just using tcp/udp syslog inputs with a single elasticsearch output

**Host/Environment (please complete the following information):**
 - Debian 10

**Logs**
Logstash config:
`input {
  udp {
    port => "514"
    type => "syslog"
  }

  tcp {
    port => "514"
    type => "syslog"
  }

}

output
{
                elasticsearch {
                        hosts => ["xx.xx.xx.xx:9200"]
                        user => admin
                        password => "admin"
                        ssl => true
                        ssl_certificate_verification => false
                        index           => "syslog-%{+YYYY.MM.dd}"
                        ilm_enabled => false
                        manage_template => false
                }
}`

`logstash               | Using bundled JDK: /usr/share/logstash/jdk
logstash               | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
logstash               | Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash               | [2021-08-16T11:37:18,326][INFO ][logstash.runner          ] Log4j configuration path used is: /usr/share/logstash/config/log4j2.properties
logstash               | [2021-08-16T11:37:18,335][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.13.2", "jruby.version"=>"jruby 9.2.16.0 (2.5.7) 2021-03-03 f82228dc32 OpenJDK 64-Bit Server VM 11.0.11+9 on 11.0.11+9 +indy +jit [linux-x86_64]"}
logstash               | [2021-08-16T11:37:19,302][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
logstash               | [2021-08-16T11:37:19,722][INFO ][org.reflections.Reflections] Reflections took 39 ms to scan 1 urls, producing 24 keys and 48 values
logstash               | [2021-08-16T11:37:20,443][WARN ][deprecation.logstash.inputs.udp] Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.
logstash               | [2021-08-16T11:37:20,640][WARN ][deprecation.logstash.outputs.elasticsearch] Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.
logstash               | [2021-08-16T11:37:20,698][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//xx.xx.xx.xx9200"]}
logstash               | [2021-08-16T11:37:20,727][WARN ][logstash.outputs.elasticsearch][main] ** WARNING ** Detected UNSAFE options in elasticsearch output configuration!
logstash               | ** WARNING ** You have enabled encryption but DISABLED certificate verification.
logstash               | ** WARNING ** To make sure your data is secure change :ssl_certificate_verification to true
logstash               | [2021-08-16T11:37:21,012][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://admin:xxxxxx@xx.xx.xx.xx:9200/]}}
logstash               | [2021-08-16T11:37:21,872][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"https://admin:xxxxxx@xx.xx.xx.xx:9200/"}
logstash               | [2021-08-16T11:37:21,914][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (1.0.0) {:es_version=>1}
logstash               | [2021-08-16T11:37:21,931][ERROR][logstash.outputs.elasticsearch][main] Unable to get license information {:url=>"https://admin:xxxxxx@xx.xx.xx.xx:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :message=>"Got response code '400' contacting Elasticsearch at URL 'https://xx.xx.xx.xx:9200/_license'"}
logstash               | [2021-08-16T11:37:21,936][ERROR][logstash.outputs.elasticsearch][main] Could not connect to a compatible version of Elasticsearch {:url=>"https://admin:xxxxxx@xx.xx.xx.xx:9200/"}
logstash               | [2021-08-16T11:37:22,009][ERROR][logstash.outputs.elasticsearch][main] Unable to retrieve Elasticsearch cluster uuid {:message=>"No Available connections", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.0.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:381:in `with_connection'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.0.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:292:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.0.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:300:in `block in get'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.0.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:199:in `get'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.0.2-java/lib/logstash/plugin_mixins/elasticsearch/common.rb:152:in `discover_cluster_uuid'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.0.2-java/lib/logstash/outputs/elasticsearch.rb:308:in `finish_register'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.0.2-java/lib/logstash/outputs/elasticsearch.rb:279:in `block in register'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.0.2-java/lib/logstash/plugin_mixins/elasticsearch/common.rb:145:in `block in after_successful_connection'"]}
logstash               | [2021-08-16T11:37:22,056][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>500, "pipeline.sources"=>["/usr/share/logstash/pipeline/logstash.conf"], :thread=>"#<Thread:0x24c95f66 run>"}
logstash               | [2021-08-16T11:37:22,776][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>0.72}`

**Comment by dblock** [comment]
When you say that you are using "logstash-oss from OpenSearch itself", where did you download it from? 

From the logs it looks like you are using logstash-output-elasticsearch 11.0.2. You want [logstash-output-opensearch](https://rubygems.org/gems/logstash-output-opensearch) which doesn't have those license checks.

**Comment by itsul** [comment]
We use the docker image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.13.2
We followed the instructions from https://opensearch.org/docs/clients/logstash/index/ (docker pull opensearchproject/logstash-oss-with-opensearch-output-plugin:7.13.2) and just wrapped it with a docker-compose.yml file.

Is there any other version that is not in the documentation?

If we leave the version empty, the latest version seems to be up-to-date:
```
docker pull opensearchproject/logstash-oss-with-opensearch-output-plugin
Using default tag: latest
latest: Pulling from opensearchproject/logstash-oss-with-opensearch-output-plugin
Digest: sha256:8f9991d0b27ef3c60c4b570ad38fb46937993c366a1892238b01cc26cb19ac83
Status: Image is up to date for opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
docker.io/opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
```

**Comment by VijayanB** [comment]
@itsul You downloaded the right image and latest version. We added new output plugin called "openserach" that will help you to connect top OpenSearch clusters. Can you updated your logstash config file as file and try again

```
input {
  udp {
    port => "514"
    type => "syslog"
  }

 tcp {
   port => "514"
   type => "syslog"
  }

}

output
{
  opensearch {
    hosts => ["xx.xx.xx.xx:9200"]
    user => admin
    password => "admin"
    ssl => true
    ssl_certificate_verification => false
    index => "syslog-%{+YYYY.MM.dd}"
 }
}

```

please let us know if you still face any issues.

**Comment by itsul** [comment]
Thanks for the quick reply. We missed the new plugin.
Maybe you can improve the documentation by adding a hint box. Logstash is working like expected now.

**Comment by dblock** [comment]
> Thanks for the quick reply. We missed the new plugin.
> Maybe you can improve the documentation by adding a hint box. Logstash is working like expected now.

Good idea! Please open an issue/contribute to https://github.com/opensearch-project/documentation-website.

**Comment by ssi0202** [comment]
hi how would this work in a windows platform do i download the latest OSS Version of logstash and the from a command line install the plugin manually

like tihs `bin/logstash-plugin install logstash-output-opensearch`

**Comment by VijayanB** [comment]
Hi @ssi0202 
We haven't tested with windows os. Since we published it in rubygems repo, I believe it should work like you suggested. Please create an issue if it didn't work, we will look into it.
