### ISSUE TITLE
Introduce an "auth_type" setting for the output plugin

### ISSUE THREAD

**Issue by elfisher** [opensearch-project/logstash-output-opensearch#59]
**Is your feature request related to a problem? Please describe.**
There are multiple authentication mechanisms for OpenSearch (Basic, OpenID, and more). There are also multiple authentication mechanisms for vendors that offer OpenSearch products. Currently the Logstash output plugin supports basic authentication and TLS. This plugin can be extended to support additional authentication mechanisms with a `auth_type` flag. 

**Describe the solution you'd like**
By adding a setting for `auth_type` users could express additional authentication mechanisms. For example someone using AWS IAM signing could express
```
output {
    opensearch {
        hosts       => "https://hostname:port"
        auth_type => {
            type => aws_iam
            aws_access_key_id => 'ACCESS_KEY'
            aws_secret_access_key => 'SECRET_KEY'
        }
        index       => "logstash-logs-%{+YYYY.MM.dd}"
    }
}
```
**NOTE** if no type is provided the default could remain basic auth (as it is today) in order to be backwards compatible.

**Comment by VijayanB** [comment]
should we call "auth" instead of auth_type?

**Comment by VijayanB** [comment]
@elfisher @vamshin @jmazanec15 @naveentatikonda what do you think?
