### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/logstash-output-opensearch#79]
Add documentation to show usage on AWS IAM and auth_type as updated configuration.

**Comment by dlvenable** [comment]
I'd like to see some more documentation in the project `README.md` file. And a full configuration reference would be helpful. I can create a separate GitHub issue if you'd prefer.

**Comment by VijayanB** [comment]
@dlvenable Thanks for feedback. In the past, we have decided to keep all documentation at https://github.com/opensearch-project/documentation-website . Do you think having more example config at README will be more beneficial?

**Comment by dlvenable** [comment]
I think having a little more in the README.md is helpful. Many developers often end up on GitHub first. And I do find it a good starting point myself.

I'd probably suggest:

* Updating the title. It just says "Logstash Plugin"
* A brief introduction to what the plugin is actually doing.
* A sample configuration file

**Comment by VijayanB** [comment]
@naveentatikonda Can you add this to README or USERGUIDE? Thanks
