### ISSUE TITLE
Update Docker image

### ISSUE THREAD

**Issue by wkruse** [opensearch-project/logstash-output-opensearch#86]
`logstash-output-opensearch` **1.1.0** was released on **22.09.2021**, but the official Docker image `opensearchproject/logstash-oss-with-opensearch-output-plugin` was not updated yet. 

Could we get a Docker image with `logstash-output-opensearch:1.1.0` please?

**Comment by VijayanB** [comment]
logstash-output-opensearch plugin v1.1.0 is now available as part of docker image as well

```
docker pull opensearchproject/logstash-oss-with-opensearch-output-plugin:7.13.4
docker pull opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
```
